package main

import (
	"github.com/labstack/echo/v4"
	"github.com/onimarufl/testGo.git/service"
)

func main() {

	testService := service.NewHandler(
		service.New(),
	)

	e := echo.New()
	e.GET("/test", testService.GetTestService)

	e.Logger.Fatal(e.Start(":1323"))

}

type AutoGenerated struct {
	A []struct {
		SortA []struct {
			SortAA []struct {
				SortAAA1 string `json:"sortAAA1,omitempty"`
				SortAAA2 string `json:"sortAAA2,omitempty"`
			} `json:"sortAA,omitempty"`
			SortAB []struct {
				SortABB1 string `json:"sortABB1,omitempty"`
				SortABB2 string `json:"sortABB2,omitempty"`
			} `json:"sortAB,omitempty"`
		} `json:"sortA"`
	} `json:"a"`
}
